### ISSUE TITLE
Trips not found for speed adjustment modification

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#970]
I'm trying to implement a simple speed adjustment on all trip patterns of a route. When I run a single point analysis, I get an error reporting that seemingly none of the trips on that route can be found. 

![Screenshot_2020-01-11_10-27-20](https://user-images.githubusercontent.com/7830465/72206527-207eb880-345d-11ea-91c7-49896dd40e6f.png)

I was able to reproduce the errors in both Cincinnati and Portland test regions: 
1. Create an *adjust speed* modification
2. Select a route and leave all trip patterns selected
3. enter speed modification (e.g. speed factor of 2) with no segments selected. 
4. run point analysis. 

This should scale the speed on that route by 2 across all segments.

Cincinnati test region/project showing the error:
https://analysis-staging.conveyal.com/regions/5df14ce26844a22caafc8557/projects/5e19e5e0c1f0b40e3af18856

**Comment by Nate-Wessel** [comment]
It looks like this also effects modifications with just one segment/hop selected on a single trip pattern.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel can you confirm this behavior occurs on production?

**Comment by Nate-Wessel** [comment]
Like #966, I can reproduce this in staging, but it seems to work fine in production. 

I am also getting similar errors when trying to adjust dwell times. This is definitely a broader problem.

**Comment by abyrd** [comment]
@Nate-Wessel this is due to the IDs used to uniquely identify feeds when referencing trips and stops in modifications. I've been reviewing the code that handles this and with any luck may have it all back in working order tomorrow on staging.

**Comment by abyrd** [comment]
I believe this is fixed on staging and with latest R5, please let me know if you see anything similar.

**Comment by Nate-Wessel** [comment]
I'm still getting a similar error in https://analysis-staging.conveyal.com/regions/5df14ce26844a22caafc8557/analysis?projectId=5e14ba280b4f073985ec2d51
for a set of phased add trip patterns modifications I created a while ago. It's saying that stops can't be found. 

```
 Errors were found in the project:
while applying the modification entitled 'Branch 3'.
in modification Branch 3

    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:GLESTRw
    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFEKENo
    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFECLAi

while applying the modification entitled 'Branch 2'.
in modification Branch 2

    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFEKENo
    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFECLAi

while applying the modification entitled 'Branch 1'.
in modification Branch 1

    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFEKENo
    Could not find existing stop with GTFS ID 9e379605-201e-4c90-bf60-d930c5d895e7:PFECLAi
```

I tried to reproduce the error in a new project based on the same bundle though and wasn't able to.

**Comment by Nate-Wessel** [comment]
I think it's safe to close this now. I've been able to adjust route speeds a few times now without issue.

**Comment by Nate-Wessel** [comment]
I think I must have jinxed it :-/

I'm now seeing a similar error when using a _convert to frequency_ modification.
![Screenshot_2020-02-01_20-33-46](https://user-images.githubusercontent.com/7830465/73601594-38180100-4532-11ea-9a42-4d676a96aa22.png)

That `null` at the end looks pretty suspicious. 

The project is:
https://analysis-staging.conveyal.com/regions/5e2dc25a7d0f5225fe06962c/analysis?projectId=5e2dc3d97d0f5225fe06963a
And I'm using the latest build of r5, `v4.7.1-158-g8de7a8b`

**Comment by abyrd** [comment]
I think the problem here is that the UI is not warning you you didn't select an example trip from which to derive the frequency-based service. It's letting you save the incomplete modification and try to route on it. We definitely need to update the documentation on how this modification type works - it's not immediately obvious.
